### ISSUE TITLE
DOA6 modding

### ISSUE THREAD

**Issue by Chem-pro** [leotorrez/XXMITools#11]
I am using this addon for Blender 4.2 to Import/Export .ib+.vb for DOA6 modding
in Blender 2.83 I had the option to "Assign new 3DMigoto vertex groups"
![image](https://github.com/user-attachments/assets/9a7341c5-1f3a-4484-9425-f9ffc733c163)
but for the new version I can't find that
![image](https://github.com/user-attachments/assets/8d0f37ea-30fe-474f-b2b5-429dabfbbcc7)
Do you have any idea How can I "Assign new 3DMigoto vertex groups"?

**Comment by TerminalAide0017** [comment]
Hello, first let me start by saying this version is heavily modified for use on some specific games, so if it works that's fantastic, but it could have issues we may not be able to fix immediately.

Second, can you describe the functionality of what exactly assigning a 3dmigoto vertex group was intended to do? As far as I know, you only need to ensure that the vertex groups are in the same order as the import in order for them to correctly export, this was true for the version of the 3dmigoto plugin this was forked from.

**Comment by Chem-pro** [comment]
Hello!
it's about .vgmap file
lets say I have a .vb file with only two vertex groups
![image](https://github.com/user-attachments/assets/437a51fe-a78f-40af-94e4-798553022c01)
it's .vgmap look like this 
![image](https://github.com/user-attachments/assets/3f2bf2f8-4d60-4ca6-a0b2-0906cc5abab6)
and I merged a mesh to this .vb with more vertex groups
https://github.com/user-attachments/assets/1bf122a3-8f6c-4187-8fd5-2c409b88ccfa
In more advanced level
https://github.com/user-attachments/assets/a77b2e19-f93b-481b-9d55-ad1a8ac096f5

**Comment by Chem-pro** [comment]
I don't know much
 maybe this will help 
this is the version am using for Blender 2.83
[blender_3dmigoto.py.txt](https://github.com/user-attachments/files/17508237/blender_3dmigoto.py.txt)

```
class UpdateVGMap(bpy.types.Operator):
    """Assign new 3DMigoto vertex groups"""
    bl_idname = "mesh.update_migoto_vertex_group_map"
    bl_label = "Assign new 3DMigoto vertex groups"
    bl_options = {'UNDO'}

    vg_step = bpy.props.IntProperty(
            name="Vertex group step",
            description='If used vertex groups are 0,1,2,3,etc specify 1. If they are 0,3,6,9,12,etc specify 3',
            default=1,
            min=1,
            )

    def invoke(self, context, event):
        wm = context.window_manager
        return wm.invoke_props_dialog(self)

    def execute(self, context):
        try:
            keywords = self.as_keywords()
            update_vgmap(self, context, **keywords)
        except Fatal as e:
            self.report({'ERROR'}, str(e))
        return {'FINISHED'}
```

**Comment by leotorrez** [comment]
This is very interesting. Because the functionality was originally made for DOA6 and we never got to experiment it first hand. In fear of implementing it wrongly, we avoided adding it when reworking some stuff. After checking the information you've shown I can infer the information we needed to add this functionality back. 

Do you happen to have a full .remap file to serve as test example or perhaps a blender project?

As for DOA6 specifically you can still use the original plugin to use remap from:[https://github.com/DarkStarSword/3d-fixes]( https://github.com/DarkStarSword/3d-fixes)

I believe that one was originally made with that game in mind so might just work fine. It has been updated quite a lot over the years.

If you intend to use the functionalities in xxmitools for DOA however, we will need some time to fix this issue. Do update me with more about your project and how you found this tool. I'm curious and moreso about your application for it.

**Comment by Chem-pro** [comment]
Here is a .7z file including DOA6 .g1m file extracted with the .g1m itself
a blend file that I imported the extracted file
https://mega.nz/file/tkoGkQ5K#3vcn75-A4tmIfsJdzUujCgZj9w_qQRHY6QwiFhzZUHQ
I already tested that https://github.com/DarkStarSword/3d-fixes/blob/master/blender_3dmigoto.py addon
but I still can't find that option ""Assign new 3DMigoto vertex groups""
any option with "mesh" not show in new blender versions 
![image](https://github.com/user-attachments/assets/2a19ced5-2a03-41d7-955c-bfd425b9debc)
I think they changed "Python API" to something else but I don't know how to find it.

**Comment by leotorrez** [comment]
Interestingly it seems that they have the code for it in their plugin but for some reason is not showing where it should- I will research it later and push a PR if I find a fix. In the mean time, thanks for the example project. I will be able to fix VGREMAP for this plugin as well with this info

**Comment by Chem-pro** [comment]
using ChatGPT I was able to make a button for "Assign new 3DMigoto vertex groups" and "Vertex group step" for this https://github.com/DarkStarSword/3d-fixes/blob/master/blender_3dmigoto.py
to work fine for Blender 4.2
![image](https://github.com/user-attachments/assets/cc366209-448a-475b-9801-31ee651fdad3)
