### ISSUE TITLE
Questions about exports

### ISSUE THREAD

**Issue by PiaoLiangDeGua** [leotorrez/XXMITools#15]
How can I use xxmi to export all the things in the collection like JoinMeshes.py?
Does it not have this feature?
![屏幕截图 2024-11-27 172712](https://github.com/user-attachments/assets/b607d3cd-8e70-44d7-9d8d-0d950fa4723e)

**Comment by PiaoLiangDeGua** [comment]
I turned on the JoinMeshes option
![屏幕截图 2024-11-27 174811](https://github.com/user-attachments/assets/b50185dd-f9dc-4919-a7f4-8af9e9d62aed)

**Comment by PiaoLiangDeGua** [comment]
I reinstalled it and now it's working properly

**Comment by leotorrez** [comment]
Glad you managed to fix it on your own. It might have been some odd blender bug when you just install an addon. As a good practice always restart blender after messing with addon enabling installing and disabling
