### ISSUE TITLE
[enhancement] Please support import/export model with UINT blend indices.

### ISSUE THREAD

**Issue by josh6688** [leotorrez/XXMITools#3]
I'm working on a far distance LoD model of an NPC in zzz (Sjal, to be exactly). The data format of the model's BLENDINDICES is R16G16B16A16_FLOAT, instead of UINT.

 (Actually, the model doesn't have BLENDINDICES or BLENDWEIGHT section in it's vb at all in the frame analyze output. Instead, it have 2 extra texcoord section in R16G16B16A16_FLOAT format. I manually renamed these 2 sections to BLENDINDICES or BLENDWEIGHT in the vb txt file. The result makes sense.)

I have managed to import the model with float indices to blender with a small edit to `datahandling.py`. But BLENDINDICES in the mod output is still stored in UINT format, which can't be reconized by game, and the character freeze in A-pose.

![image](https://github.com/user-attachments/assets/8606db1e-8389-49ad-94ca-2d49d03c796b)
Normally she should look like this: 
![image](https://github.com/user-attachments/assets/8960b9e6-fcff-4422-9fe8-c76fbc9c76cb)

**Comment by leotorrez** [comment]
I believe this has been resolved since last update to the dev section. Will look into it in more detail and update you shortly

**Comment by leotorrez** [comment]
I forgot to update you on it- But the issue was solved at the time already
