### ISSUE TITLE
"Missing textures when exporting using zzz."

### ISSUE THREAD

**Issue by newandstar** [leotorrez/XXMITools#7]
Thank you very much for providing the tool. I encountered some issues while using it. When exporting the zzz mod with xxmi tools, some textures are missing, and the ini file does not reference them. The missing textures have a common characteristic: they are all the same. If this is a feature of xxmi, I hope a toggle can be added so that users can choose it  
![57925dee-8c1d-40f2-a5b5-5a557dcf2c4e](https://github.com/user-attachments/assets/c7ea2199-492a-4fc6-b140-e966133c4b8a)
![e8fced8f7645d9d2b89d976ccded0976](https://github.com/user-attachments/assets/89b8088c-485b-4477-9b39-58926b966ec2)

**Comment by newandstar** [comment]
This picture is clearer.

![9cc86718-6558-4fcf-8819-cd03dc379691](https://github.com/user-attachments/assets/49aa477e-b845-45e3-add6-9d23dfc11839)

**Comment by leotorrez** [comment]
![image](https://github.com/user-attachments/assets/e4ad8b8e-2cdd-40ca-b5cb-d269366ceeb2)
You are clearly using a modified version of the script. I recommend deleting it and installing the one in releases in this repository. Otherwise I can't provide support for you

**Comment by newandstar** [comment]
Sorry. Actually, this is caused by my choice of Blender language, not because I'm using a modified version. You can try importing Nicole or Nekomata using xxmi without making any changes, then exporting it again; it will be missing some of the same textures.

**Comment by leotorrez** [comment]
I can't replicate your issue. Test in the latest version of this non modified script. Whatever your custom version is might be causing issues. For me works as intended with the use of the latest version and dumps from https://github.com/leotorrez/ZZ-Model-Importer-Assets/tree/main/PlayerCharacterData
